# Generated by Django 5.1.1 on 2024-10-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fooditems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=500)),
                ('itemprice', models.CharField(max_length=50)),
                ('itemcategory', models.CharField(max_length=50)),
                ('itemdescription', models.CharField(max_length=500)),
                ('itemimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
