# Generated by Django 5.1.1 on 2024-10-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0002_fooditems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=50)),
                ('categoryimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
