# Generated by Django 5.1.1 on 2024-10-18 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0003_foodcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='itemcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodies.foodcategory'),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='itemdescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='itemimage',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='itemname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='itemprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
