# Generated by Django 5.1.1 on 2024-10-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0004_alter_fooditems_itemcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=50)),
                ('itemid', models.CharField(max_length=7)),
                ('username', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=50)),
                ('itemdescription', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='fullname',
            new_name='username',
        ),
    ]
