# Generated by Django 5.1.1 on 2024-10-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='itemprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
