# Generated by Django 5.1.1 on 2024-10-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0007_alter_cart_itemprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=50)),
                ('itemid', models.CharField(max_length=7)),
                ('userid', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('cart_status', models.IntegerField(default=1)),
                ('itemprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
