# Generated by Django 5.1.1 on 2024-10-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0010_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='cart_status',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wishliststatus',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
