# Generated by Django 5.1.1 on 2024-10-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0011_remove_wishlist_cart_status_wishlist_wishliststatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=50)),
                ('itemimage', models.ImageField(upload_to='')),
                ('offerdetails', models.CharField(max_length=50)),
            ],
        ),
    ]
