# Generated by Django 5.1.1 on 2024-10-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0012_special_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='itemimage',
            field=models.URLField(),
        ),
    ]
