# Generated by Django 5.1.1 on 2024-10-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0013_alter_fooditems_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='categoryimage',
            field=models.URLField(),
        ),
    ]
