# Generated by Django 5.1.1 on 2024-10-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0014_alter_foodcategory_categoryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special_offer',
            name='offerdetails',
            field=models.URLField(),
        ),
    ]
