# Generated by Django 5.1.1 on 2024-10-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0015_alter_special_offer_offerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special_offer',
            name='itemimage',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='special_offer',
            name='offerdetails',
            field=models.CharField(max_length=200),
        ),
    ]
