# Generated by Django 5.1.1 on 2024-11-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0018_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='itemimage',
            field=models.URLField(),
        ),
    ]
