# Generated by Django 5.1.1 on 2024-11-06 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0019_alter_placeorder_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodies.login'),
        ),
    ]
